name: look
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_inappwebview: ^4.0.0+4
  #flutter_inappwebview: ^4.0.0+4
  # The following adds the shared pref as a dependency in your application
  shared_preferences: ^0.5.10

  # Flogs, a powerful logging framework
  f_logs: ^1.2.2

  # Firebase google servicesic_launcher.png
  #ic_launcher_foreground.png
  #ic_launcher_round.pngic_launcher.png
  #ic_launcher_foreground.png
  #ic_launcher_round.png
  firebase_core: ^0.5.2+1
  firebase_messaging: ^7.0.3

  #to keep your code and project structure mantainable and reusable
  flutter_modular: ^2.0.1
  # MobX is a library for reactively managing the state of your applications. Use the power of
  # observables, actions, and reactions to supercharge your Dart and Flutter apps.
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2
  # Toast
  oktoast: ^2.3.0
  # An helper to easily exposes a value using InheritedWidget without having to write one.
  provider: ^4.3.2+1

  # String validation and sanitization for Dart. Dart 2-compatible version of validator
  validators: ^2.0.1

  # A flexible widget for user notification. Customize your text, button, duration, animations
  # and much more. For Android devs, it is made to replace Snackbars and Toasts.
  flushbar: ^1.10.4

  # Material Dialog
  material_dialog: ^0.0.9

  # This package provides internationalization and localization facilities, including message
  # translation, plurals and genders, date/number formatting and parsing, and bidirectional text.
  intl: ^0.16.0

  #cusom ICONS package
  flutter_vector_icons: ^0.2.1
  line_icons: ^0.2.0
  flutter_svg: ^0.19.0
  font_awesome_flutter: ^8.5.0
  # A powerful Http client for Dart
  dio: 3.0.10

  # loading progress
  floading: ^1.0.2
  #cached_network_image
  cached_network_image: ^2.5.0
  # Dependency injection
  data_connection_checker: ^0.3.4
  inject:
    git:
      url: https://github.com/google/inject.dart.git
      path: package/inject
      ref: 7c3cbf6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # For information on the generic Dart part of this file, see the
  # following page: https://dart.dev/tools/pub/pubspec
  # The following adds the launcher icon support to your application.
  # run below mentioned commands to generate launcher icons
  # flutter packages get
  # flutter packages pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.8.0
  mobx_codegen: ^1.1.0+2
  json_serializable: ^3.4.0
  build_runner: ^1.10.1
  source_gen: 0.9.6
  analyzer: ^0.39.1
  inject_generator:
    git:
      url: https://github.com/google/inject.dart.git
      path: package/inject_generator
      ref: 7c3cbf6

flutter_icons:
  image_path: "assets/icons/ic_launcher.png"
  android: true
  ios: true
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/gif/
    - assets/icons/
    - assets/lang/
    - assets/res/
    - assets/intro/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/Product-Sans-Regular.ttf
        - asset: assets/fonts/Product-Sans-Italic.ttf
          style: italic
        - asset: assets/fonts/Product-Sans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GEDinarTwo-Medium.otf
        - asset: assets/fonts/GEDinarTwo-Light-Italic.otf
          style: italic
        - asset: assets/fonts/GEDinarTwo-Medium-Italic.otf
          style: italic
        - asset: assets/fonts/GESSTwo_Bold.otf
          weight: 700
        - asset: assets/fonts/GESSTWO_MEDIUM.otf
    - family: GEDinarTwo
      fonts:
        - asset: assets/fonts/GEDinarTwo-Medium.otf
        - asset: assets/fonts/GEDinarTwo-Light-Italic.otf
          style: italic
        - asset: assets/fonts/GEDinarTwo-Medium-Italic.otf
          style: italic
        - asset: assets/fonts/GESSTwo_Bold.otf
          weight: 700
        - asset: assets/fonts/GESSTWO_MEDIUM.otf
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Bold.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
